version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shareit
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=production
      - PORT=5555
    volumes:
      - /tmp/shareit/logs:/app/logs
      - /tmp/shareit/:/app/upload
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 